Repository Team-MediFit/MediFit-BE, pull requests merged in 2025-05, with the labels that each got.

#2 [MF-2] 스웨거 설정
  build.gradle
  src/main/java/com/medifitbe/core/config/SwaggerConfig.java
Labels: chore

#3 [MF-3] 구독자 정보 저장
  src/main/java/com/medifitbe/core/config/JpaAuditingConfig.java
  src/main/java/com/medifitbe/core/entity/TimeBaseEntity.java
  src/main/java/com/medifitbe/user/adapter/SubscriberApi.java
  src/main/java/com/medifitbe/user/adapter/SubscriberController.java
  src/main/java/com/medifitbe/user/adapter/in/request/CreateSubscriberRequest.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/SubscriberPersistenceAdapter.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/entity/SubscriberEntity.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/repository/SubscriberRepository.java
  src/main/java/com/medifitbe/user/application/port/in/CreateSubscriberUseCase.java
  src/main/java/com/medifitbe/user/application/port/out/CreateSubscriberPort.java
  src/main/java/com/medifitbe/user/application/service/CreateSubscriberService.java
  src/main/java/com/medifitbe/user/domain/CareerType.java
  src/main/java/com/medifitbe/user/domain/Department.java
  src/main/java/com/medifitbe/user/domain/RegionMajor.java
  src/main/java/com/medifitbe/user/domain/Subscriber.java
  src/main/java/com/medifitbe/user/domain/WageUnit.java
  src/main/java/com/medifitbe/user/domain/WeekendWork.java
  src/main/java/com/medifitbe/user/domain/Welfare.java
  src/main/java/com/medifitbe/user/domain/WorkType.java
  src/main/java/com/medifitbe/user/domain/Workday.java
  src/main/java/com/medifitbe/user/mapper/SubscriberMapper.java
Labels: feat

#4 [MF-4] 이메일 서비스 추가
  build.gradle
  src/main/java/com/medifitbe/mail/adapter/in/MailController.java
  src/main/java/com/medifitbe/mail/adapter/in/request/BroadcastMailRequest.java
  src/main/java/com/medifitbe/mail/application/service/EmailBroadcastService.java
  src/main/java/com/medifitbe/mail/application/service/MailService.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/repository/SubscriberRepository.java
Labels: feat

#5 [MF-5] 병원 구직 데이터 조회 및 저장
  src/main/java/com/medifitbe/jobdata/adapter/JobValidationController.java
  src/main/java/com/medifitbe/jobdata/adapter/in/request/JobDataRequest.java
  src/main/java/com/medifitbe/jobdata/adapter/in/response/JobDataResponse.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/entity/JobDataEntity.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/entity/ValidatedJobDataEntity.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/repository/JobDataRepository.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/repository/ValidatedJobDataRepository.java
  src/main/java/com/medifitbe/jobdata/application/service/JobValidationService.java
Labels: feat

#6 [MF-6] CICD 파이프라인 구축
  .github/workflows/dev-deploy.yml
  Dockerfile
  compose.yaml
  infra/deploy/docker-compose.yml
  infra/deploy/scripts/deploy.sh
Labels: ci/cd

#7 [MF-7] 크롤링 데이터를 자동 저장
  src/main/java/com/medifitbe/jobdata/adapter/JobPostingController.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/entity/JobDataEntity.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/entity/ValidatedJobDataEntity.java
  src/main/java/com/medifitbe/jobdata/application/service/JobPostingService.java
Labels: fix, feat

#9 [MF-8] 지역 디비 저장 방식을 변경
  src/main/java/com/medifitbe/user/adapter/in/request/CreateSubscriberRequest.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/entity/RegionGroupEntity.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/entity/SubscriberEntity.java
  src/main/java/com/medifitbe/user/domain/Department.java
  src/main/java/com/medifitbe/user/domain/RegionGroup.java
  src/main/java/com/medifitbe/user/domain/Subscriber.java
  src/main/java/com/medifitbe/user/mapper/SubscriberMapper.java
Labels: refactor

#11 [MF-9] 맞춤구직 매칭 서비스
  build.gradle
  src/main/java/com/medifitbe/core/config/SchedulerConfig.java
  src/main/java/com/medifitbe/jobdata/adapter/JobRecommendationController.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/entity/JobRecommendationHistoryEntity.java
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/repository/JobRecommendationHistoryRepository.java
  src/main/java/com/medifitbe/jobdata/application/dto/JobEmailDto.java
  src/main/java/com/medifitbe/jobdata/application/service/JobRecommendationEngine.java
  src/main/java/com/medifitbe/jobdata/application/service/JobRecommendationService.java
  src/main/java/com/medifitbe/jobdata/domain/JobRecommendation.java
  src/main/java/com/medifitbe/mail/adapter/in/MailController.java
  src/main/java/com/medifitbe/mail/application/service/EmailBroadcastService.java
  src/main/java/com/medifitbe/mail/application/service/MailService.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/repository/SubscriberRepository.java
  src/main/java/com/medifitbe/user/domain/Subscriber.java
  src/main/java/com/medifitbe/user/mapper/SubscriberMapper.java
  src/main/resources/templates/email.html
Labels: chore, feat

#13 [MF-11] 맞춤공고 서비스 추전 방식 수정
  src/main/java/com/medifitbe/jobdata/adapter/out/persistence/repository/JobRecommendationHistoryRepository.java
  src/main/java/com/medifitbe/jobdata/application/service/JobRecommendationEngine.java
  src/main/java/com/medifitbe/jobdata/application/service/JobRecommendationService.java
  src/main/java/com/medifitbe/mail/application/service/EmailBroadcastService.java
Labels: refactor, feat

#15 [MF-13] enum 값 매칭되도록 수정
  src/main/java/com/medifitbe/user/domain/WeekendWork.java
  src/main/java/com/medifitbe/user/domain/Welfare.java
Labels: fix

#16 [MF-14] 구독자 정보 삭제
  src/main/java/com/medifitbe/user/adapter/SubscriberApi.java
  src/main/java/com/medifitbe/user/adapter/SubscriberController.java
  src/main/java/com/medifitbe/user/adapter/in/request/CreateSubscriberRequest.java
  src/main/java/com/medifitbe/user/adapter/in/request/DeleteSubscriberRequest.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/SubscriberPersistenceAdapter.java
  src/main/java/com/medifitbe/user/adapter/out/persistence/repository/SubscriberRepository.java
  src/main/java/com/medifitbe/user/application/port/in/DeleteSubscriberUseCase.java
  src/main/java/com/medifitbe/user/application/port/out/DeleteSubscriberPort.java
  src/main/java/com/medifitbe/user/application/service/CreateSubscriberService.java
  src/main/java/com/medifitbe/user/application/service/DeleteSubscriberService.java
Labels: feat
